soiree_soiree:
    resource: "@SoireeBundle/Resources/config/routing/soiree.yml"
    prefix:   /soiree

soiree_participation:
    resource: "@SoireeBundle/Resources/config/routing/participation.yml"
    prefix:   /participation
