<?php

namespace SoireeBundle\Repository;

/**
 * ParticipationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipationRepository extends \Doctrine\ORM\EntityRepository
{

    public function getNbParticipantsSoiree($id_soiree)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT COUNT(p.id) FROM SoireeBundle:Participation p WHERE p.soiree = :idSoiree')
            ->setParameter('idSoiree', $id_soiree)
            ->getSingleScalarResult();
    }

    public function getParticipantsSoiree($id_soiree)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT (u.username) FROM SoireeBundle:Participation p LEFT JOIN p.participant u WHERE p.soiree = :idSoiree')
            ->setParameter('idSoiree', $id_soiree)
            ->getResult();
    }

}

//    public function getNbParticipantsSoiree($id_soiree)
//    {
//        return $this->createQueryBuilder('id')
//            ->select('COUNT(id)')
//            ->where('soiree = :idSoiree')
//            ->setParameter('idSoiree', $id_soiree)
//            ->getQuery()
//            ->getSingleScalarResult();
//    }


//public function getParticipantsSoiree($id_soiree)
//{
//    return $this->getEntityManager()
//        ->createQuery('SELECT (p.participant) FROM SoireeBundle:Participation p WHERE p.soiree = :idSoiree')
//        ->setParameter('idSoiree', $id_soiree)
//        ->getResult();
//}

//    public function getNbParticipantsSoiree2($id_soiree)
//    {
//        return $this->getEntityManager()
//            ->createQuery(
//                'SELECT COUNT id FROM SoireeBundle:Participation p WHERE p.soiree_id = :idSoiree'
//            )->setParameter('idSoiree', $id_soiree)
//            ->getResult();
//    }
//$query = $em->createQuery('SELECT u.name FROM CmsUser u WHERE u.id IN(46)');
//$usernames = $query->getResult();

