SoireeBundle\Entity\Participation:
    type: entity
    table: participation
    repositoryClass: SoireeBundle\Repository\ParticipationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        participant:
            targetEntity: UtilBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id
        soiree:
            targetEntity: SoireeBundle\Entity\Soiree
            joinColumn:
                name: soiree_id
                referencedColumnName: id
    lifecycleCallbacks: {  }

